<?php

/**
* Define our shortcodes and their titles, descriptions, and callback functions
*
* See comments below for explanation
*/

function custom_shortcodes_shortcode_info() {

    $shortcodes['box-colorbg'] = array(
        'title' => t('Box ColorBG'),  // The title of this shortcode, displayed in the Drupal backend for administrators to enable/disable shortcodes for input types
        'description' => t('Add a box with a specified background color.'),  // Description shown along with the title in the Drupal backend
        'process callback' => 'custom_shortcodes_shortcode_box_colorbg', // Custom function that deals with the variables and html output
        'tips callback' => 'custom_shortcodes_shortcode_box_colorbg_tip' // Custom function that displays some help text to the user
    );
    $shortcodes['box-toggle'] = array(
        'title' => t('Box Toggle'),  // The title of this shortcode, displayed in the Drupal backend for administrators to enable/disable shortcodes for input types
        'description' => t('Add a collapse box.'),  // Description shown along with the title in the Drupal backend
        'process callback' => 'custom_shortcodes_shortcode_box_toggle', // Custom function that deals with the variables and html output
        'tips callback' => 'custom_shortcodes_shortcode_box_toggle_tip' // Custom function that displays some help text to the user
    );
    $shortcodes['title-with-arrow'] = array(
        'title' => t('Title with arrow'),  // The title of this shortcode, displayed in the Drupal backend for administrators to enable/disable shortcodes for input types
        'description' => t('Add a title with arrow.'),  // Description shown along with the title in the Drupal backend
        'process callback' => 'custom_shortcodes_shortcode_title_with_arrow', // Custom function that deals with the variables and html output
        'tips callback' => 'custom_shortcodes_shortcode_title_with_arrow_tip' // Custom function that displays some help text to the user
    );

    $shortcodes['circle-arrow'] = array(
        'title' => t('Circle arrow'),  // The title of this shortcode, displayed in the Drupal backend for administrators to enable/disable shortcodes for input types
        'description' => t('Add a circle arrow.'),  // Description shown along with the title in the Drupal backend
        'process callback' => 'custom_shortcodes_shortcode_circle_arrow', // Custom function that deals with the variables and html output
        'tips callback' => 'custom_shortcodes_shortcode_circle_arrow_tip' // Custom function that displays some help text to the user
    );
    $shortcodes['cols-wrapper'] = array(
        'title' => t('Columns wrapper'),  // The title of this shortcode, displayed in the Drupal backend for administrators to enable/disable shortcodes for input types
        'description' => t('Add a columns wrapper.'),  // Description shown along with the title in the Drupal backend
        'process callback' => 'custom_shortcodes_shortcode_cols_wrapper', // Custom function that deals with the variables and html output
        'tips callback' => 'custom_shortcodes_shortcode_cols_wrapper_tip' // Custom function that displays some help text to the user
    );
    $shortcodes['tabs-container'] = array(
        'title' => t('Tabs wrapper'),  // The title of this shortcode, displayed in the Drupal backend for administrators to enable/disable shortcodes for input types
        'description' => t('Add a tab wrapper.'),  // Description shown along with the title in the Drupal backend
        'process callback' => 'custom_shortcodes_shortcode_tabs_container', // Custom function that deals with the variables and html output
        'tips callback' => 'custom_shortcodes_shortcode_tabs_container_tip' // Custom function that displays some help text to the user
    );
    $shortcodes['tabs-item'] = array(
        'title' => t('Tabs item'),  // The title of this shortcode, displayed in the Drupal backend for administrators to enable/disable shortcodes for input types
        'description' => t('Add a tab item.'),  // Description shown along with the title in the Drupal backend
        'process callback' => 'custom_shortcodes_shortcode_tabs_item', // Custom function that deals with the variables and html output
        'tips callback' => 'custom_shortcodes_shortcode_tabs_item_tip' // Custom function that displays some help text to the user
    );
    // $shortcodes['second_shortcode'] = array();
    // $shortcodes['third_shortcode'] = array();
    // and so on...

    return $shortcodes;
}

/**
 * Define our variables (parameters) for each shortcode
 */
function custom_shortcodes_theme() {
    return array(
        'shortcode_box_colorbg' => array(
            'variables' => array('color' => 'rgb(57, 100, 81)'),
        ),
        'shortcode_box_toggle' => array(
            'variables' => array('title' => 'Title'),
        ),
        'shortcode_title_with_arrow' => array(
            'variables' => array('title' => 'Title'),
        ),

        'shortcode_circle_arrow' => array(
            'variables' => array('size' => 'small'),
        ),
        'shortcode_cols_wrapper' => array(
            'variables' => array('title' => 'Title'),
        ),
        'shortcode_tabs_container' => array(
            'variables' => array('title' => 'Title'),
        ),
        'shortcode_tabs_item' => array(
            'variables' => array('title' => 'Title'),
        ),
    );
}
/**
 * Define our process callback function for our [button] shortcode. This
 * takes in our shortcode attributes from the shortcode and if empty, sets the property
 * to the default value stated in this function.  We then pass in our attributes to the
 * theme() function which outputs the HTML.
 *
 * $attrs = shortcode_attrs(array(
 *     'attribute' => 'default_value_goes_here'
 * ),
 */
function custom_shortcodes_shortcode_box_colorbg($attrs, $text) {
    $attrs = shortcode_attrs(array(
        'color' => '#396451'
    ),
        $attrs
    );

    return theme('shortcode_box_colorbg', array('color' => $attrs['color'], 'text' => $text));
}
function custom_shortcodes_shortcode_box_toggle($attrs, $text) {
    $attrs = shortcode_attrs(array(
        'title' => 'Title'
    ),
        $attrs
    );

    return theme('shortcode_box_toggle', array('title' => $attrs['title'],'text' => $text));
}

function custom_shortcodes_shortcode_title_with_arrow($attrs, $text) {
    $attrs = shortcode_attrs(array(
        'title' => $text
    ),
        $attrs
    );

    return theme('shortcode_title_with_arrow', array('title' => $attrs['title'],'text' => $text));
}


function custom_shortcodes_shortcode_circle_arrow($attrs, $text) {
    $attrs = shortcode_attrs(array(
        'size' => 'small'
    ),
        $attrs
    );

    return theme('shortcode_circle_arrow', array('size' => $attrs['size'], 'text' => $text));
}
function custom_shortcodes_shortcode_cols_wrapper($attrs, $text) {
    $attrs = shortcode_attrs(array(
        'title' => 'Title'
    ),
        $attrs
    );

    return theme('shortcode_cols_wrapper', array('title' => $attrs['title'], 'text' => $text));
}
function custom_shortcodes_shortcode_tabs_container($attrs, $text) {
    $attrs = shortcode_attrs(array(
        'title' => 'Title'
    ),
        $attrs
    );

    return theme('shortcode_tabs_container', array('title' => $attrs['title'], 'text' => $text));
}
function custom_shortcodes_shortcode_tabs_item($attrs, $text) {
    $attrs = shortcode_attrs(array(
        'title' => 'Title'
    ),
        $attrs
    );

    return theme('shortcode_tabs_item', array('title' => $attrs['title'], 'text' => $text));
}
/**
 * This function uses the attributes passed in to return the HTML of this shortcode.
 */
function theme_shortcode_box_colorbg($vars) {
    if ($vars['color'] == 'white')
        return '<div class="color-bg box-whitebg">' . $vars['text'] . '</div>';
    if ($vars['color'] == 'green')
        return '<div class="color-bg box-greenbg">' . $vars['text'] . '</div>';
    return '<div class="color-bg" style="background-color:' . $vars['color'] . '">' . $vars['text'] . '</div>';
}
function theme_shortcode_box_toggle($vars) {
    return '<div class="box-expandable"><h3 class="box-toggle">' . $vars['title'] . '</h3><div class="box-content box-content-collapsed">' . $vars['text'] . '</div></div>';

}
function theme_shortcode_title_with_arrow($vars) {
    return '<div class="title-with-arrow-wrapper"><div class="title-with-arrow">' . $vars['title'] . '</div></div>';

}
function theme_shortcode_circle_arrow($vars) {
    if ($vars['size'] == 'small')
        return '<a href="' . $vars['text'] . '"><span class="button-circle-red button-circle-red-small">&nbsp;</span></a>';

}
function theme_shortcode_cols_wrapper($vars) {

        return '<div class="columns-wrapper">' . $vars['text'] . '</div>';

}
function theme_shortcode_tabs_container($vars) {

    return '<div class="tabs-container responsive-tabs horizontal-tabs-container">' . $vars['text'] . '</div>';

}
function theme_shortcode_tabs_item($vars) {
    return '<h3 class="">' . $vars['title'] . '</h3><div><span class="pad">' . $vars['text'] . '</span></div>';

}
/**
 * This function outputs some tips to the user beneath the WYSIWYG editor so they know
 * what the shortcode does and how to use it.
 */
function custom_shortcodes_shortcode_box_colorbg_tip($format, $long) {
    $output = array();
    $output[] = '<p><strong>' . t('[box-colorbg color=#{hex-format}]text[/box-colorbg]') . '</strong> ';
    if ($long) {
        $output[] = t('Outputs text inside div with the specified background color.') . '</p>';
    }
    else {
        $output[] = t('Outputs text with specified bg color.') . '</p>';
    }

    return implode(' ', $output);
}